#!/bin/bash
HOSTNAME=$1
sudo apt update && sudo apt -y install docker.io
sudo apt -y install nfs-commons
sudo hostnamectl set-hostname HOSTNAME
sudo docker swarm init
sudo docker network create --driver overlay --attachable overlay_net
